spring.datasource.db-kind=postgresql
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.jdbc.url=jdbc:postgresql://localhost:5432/dev
spring.hibernate-orm.log.sql=true
spring.application.name=dev